version: '3'

tasks:
  build:
    desc: Builds the executable application for the current platform
    deps: [ assets ]
    cmds:
      - go build -v -o out/ cmd/update.go

  assets:
    desc: Creates the assets using yarn
    dir: resources
    cmds:
      - yarn
      - yarn run build

  update_go:
    desc: Updates Go dependencies
    cmds:
      - go get -u ./...
      - go mod tidy

  update_yarn:
    desc: Updates Yarn dependencies
    dir: resources
    cmds:
      - yarn upgrade
      - yarn audit

  update:
    desc: Updates all dependencies
    cmds:
      - task: update_go
      - task: update_yarn
